/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author tw93
 */
public class fast extends javax.swing.JFrame {

    /**
     * Creates new form fast
     */
    public fast() {
        initComponents();
    }
    String Myaccnum;
    public fast(String accnum) {
        initComponents();
        Myaccnum=accnum;
        getbalance();
    }
     Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    int Oldbalance;
    private void getbalance(){
           String query="select *from accountb where accnum="+Myaccnum;
                   try{
                        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","vikijadhav@28");
                        st=con.createStatement();
                        rs= st.executeQuery(query);
                       if(rs.next()){
                           Oldbalance=rs.getInt(9);
                           ballab.setText(""+Oldbalance);
                          
                       }else{
                            JOptionPane.showMessageDialog(this,"wrong pin or username");
                       }
    }catch(Exception e){
         JOptionPane.showMessageDialog(this,e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hunbtn = new javax.swing.JButton();
        fibtn = new javax.swing.JButton();
        thabtn = new javax.swing.JButton();
        tenbtn = new javax.swing.JButton();
        fithabtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ballab = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("ATM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Fast Cash");

        hunbtn.setText("100");
        hunbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hunbtnMouseClicked(evt);
            }
        });

        fibtn.setText("500");
        fibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fibtnMouseClicked(evt);
            }
        });

        thabtn.setText("2000");
        thabtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thabtnMouseClicked(evt);
            }
        });

        tenbtn.setText("10000");
        tenbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenbtnMouseClicked(evt);
            }
        });

        fithabtn.setText("5000");
        fithabtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fithabtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("bal:");

        ballab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        back.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hunbtn)
                            .addComponent(thabtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fibtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fithabtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(tenbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ballab, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(back)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hunbtn)
                    .addComponent(fibtn))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ballab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thabtn)
                    .addComponent(fithabtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tenbtn)
                .addGap(41, 41, 41)
                .addComponent(back)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hunbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hunbtnMouseClicked
        // ifTODO add your handling code here:
        if(Oldbalance>=100){
         try{
        String query="update accountb set balance=? where accnum=?";
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","vikijadhav@28");
        PreparedStatement ps=con.prepareStatement(query);
        ps .setInt(1,Oldbalance-100);
        ps.setString(2,Myaccnum);
       if( ps.executeUpdate()==1){
           JOptionPane.showMessageDialog(this, "withdraw successfully"); 
           new Home(Myaccnum).setVisible(true);
        this.dispose();
       }else{
            JOptionPane.showMessageDialog(this, "missing");
       }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }else{
             JOptionPane.showMessageDialog(this, "Insufficient balance");
         }
    }//GEN-LAST:event_hunbtnMouseClicked

    private void fibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fibtnMouseClicked
        // TODO add your handling code here:
        if(Oldbalance>=500){
         try{
        String query="update accountb set balance=? where accnum=?";
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","vikijadhav@28");
        PreparedStatement ps=con.prepareStatement(query);
        ps .setInt(1,Oldbalance-500);
        ps.setString(2,Myaccnum);
       if( ps.executeUpdate()==1){
           JOptionPane.showMessageDialog(this, "withdraw successfully"); 
           new Home(Myaccnum).setVisible(true);
        this.dispose();
       }else{
            JOptionPane.showMessageDialog(this, "missing");
       }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }else{
             JOptionPane.showMessageDialog(this, "Insufficient balance");
         }
                                         
    }//GEN-LAST:event_fibtnMouseClicked
    
    private void thabtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thabtnMouseClicked
        // TODO add your handling code here:
         if(Oldbalance>=2000){
         try{
        String query="update accountb set balance=? where accnum=?";
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","vikijadhav@28");
        PreparedStatement ps=con.prepareStatement(query);
        ps .setInt(1,Oldbalance-2000);
        ps.setString(2,Myaccnum);
       if( ps.executeUpdate()==1){
           JOptionPane.showMessageDialog(this, "withdraw successfully");
           new Home(Myaccnum).setVisible(true);
        this.dispose();
       }else{
            JOptionPane.showMessageDialog(this, "missing");
       }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }else{
             JOptionPane.showMessageDialog(this, "Insufficient balance");
         }
    }//GEN-LAST:event_thabtnMouseClicked

    private void fithabtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fithabtnMouseClicked
        // TODO add your handling code here:
         if(Oldbalance>=5000){
         try{
        String query="update accountb set balance=? where accnum=?";
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","vikijadhav@28");
        PreparedStatement ps=con.prepareStatement(query);
        ps .setInt(1,Oldbalance-5000);
        ps.setString(2,Myaccnum);
       if( ps.executeUpdate()==1){
           JOptionPane.showMessageDialog(this, "withdraw successfully"); 
           new Home(Myaccnum).setVisible(true);
        this.dispose();
       }else{
            JOptionPane.showMessageDialog(this, "missing");
       }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }else{
             JOptionPane.showMessageDialog(this, "Insufficient balance");
         }
    }//GEN-LAST:event_fithabtnMouseClicked

    private void tenbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenbtnMouseClicked
        // TODO add your handling code here:
         if(Oldbalance>=10000){
         try{
        String query="update accountb set balance=? where accnum=?";
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","vikijadhav@28");
        PreparedStatement ps=con.prepareStatement(query);
        ps .setInt(1,Oldbalance-10000);
        ps.setString(2,Myaccnum);
       if( ps.executeUpdate()==1){
           JOptionPane.showMessageDialog(this, "withdraw successfully"); 
           new Home(Myaccnum).setVisible(true);
        this.dispose();
       }else{
            JOptionPane.showMessageDialog(this, "missing");
       }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }else{
             JOptionPane.showMessageDialog(this, "Insufficient balance");
         }
    }//GEN-LAST:event_tenbtnMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new Home(  Myaccnum).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel ballab;
    private javax.swing.JButton fibtn;
    private javax.swing.JButton fithabtn;
    private javax.swing.JButton hunbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tenbtn;
    private javax.swing.JButton thabtn;
    // End of variables declaration//GEN-END:variables
}
